# Generated by Django 5.2 on 2025-05-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_book_copies_sold_book_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
