# Generated by Django 5.2 on 2025-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_alter_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(default=0)),
                ('max_profit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
